### ISSUE TITLE
Magazine Layout: Adsense involved - from Magazine to Blog Layout

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#80]
Hello Develoeprs,

I can unfortunately observe the following at the magazine theme.

If I enter the Adsense code in the field provided for this purpose, the magazine layout automatically changes to the blog layout.

All magazine changes are then no longer valid and a blog layout.

I currently have PHP 5.6.

Can you please check this with the new magazine Theme.

Thanks in advance.

**Comment by semplon** [comment]
@AlexL777 ok, sure. i'll check it

**Comment by semplon** [comment]
i've already know the problem is. i'll commit it soon and see other bugs exist. if not i'll release the next update,

**Comment by AlexL777** [comment]
Okay, then we'll do it. Yes, I know, some bugs are still available. But I have simply patience, rather everything was fixed.

For now, my Genix blog works with the blog layout. SEO URLs also work. Then I have defined in the style.css the headings differently. I felt like the H2 headings were not displayed in the frontend.

A look into the style.css was however positive. H2 CSS rule was included. Nevertheless, I have defined something different. This already works.

Thank you for your time.

**Comment by semplon** [comment]
actually you can fix it by following this step : 

- open options.php at the gneex theme directory
- go to line 45, and replace this code 
   `$opt[$k] = Typo::jsonFormat($v);`
   become 
   `$opt[$k] = $v;`

- and save it. 

let me know if it works.

actually there are a lot of features for the 1.1.0 release. the problem was my laptop which had the latest update stolen and i had to rebuild again from last 1.1.0 update. one of the update was cached page. this is really good for non dynamic website and to make website load fast.

i will implement this on the next future update.

**Comment by AlexL777** [comment]
Ok, awesome. Your tips helped and I was able to integrate successful Adsense into the blog. This is now displayed via 3 Adsense banners in the frontend.

Think, so my problem is solved 👍

**Comment by semplon** [comment]
cool, glad it works

**Comment by AlexL777** [comment]
😄

**Comment by semplon** [comment]
Hi @AlexL777 , for H2 please change it here http://prntscr.com/gjcgu5 
it's at theme options -> style 
see the **Content** part

**Comment by AlexL777** [comment]
Thank you, I looked at something, but only briefly flown. Now I know where the backend is.
